name: Build and Publish image to Docker Hub
on:
  #[workflow_dispatch] # manual run via github actions
  push:
    branches:
      - ci-cd
    paths:
      - 'backend/'
      - 'frontend/'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build the backend and frontend Docker image
        #run: docker build -t dimilan/3sdevops-backend:latest ./backend
        run: |
          docker build -t dimilan/3sdevops-backend:latest ./backend 
          docker build -t dimilan/3sdevops-frontend:latest ./frontend
      - name: push images to docker hub
        run: |
          echo ${{ secrets.DOCKERHUBTOKEN }} | docker login -u dimilan --password-stdin
          docker push dimilan/3sdevops-backend:latest
          docker push dimilan/3sdevops-frontend:latest